# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-03 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text2category', '0002_auto_20190203_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.TextField(),
        ),
    ]
