# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-03 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text2category', '0003_auto_20190203_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='date',
        ),
        migrations.RemoveField(
            model_name='content',
            name='ipfn',
        ),
    ]
